# Generated by Django 4.1.2 on 2022-11-01 00:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nick_name_user_followers_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path),
        ),
    ]
