# Generated by Django 4.1.2 on 2022-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
    ]
