# Generated by Django 4.1.2 on 2022-10-11 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0006_remove_board_good_board_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='command',
            field=models.ManyToManyField(related_name='board_command', to=settings.AUTH_USER_MODEL),
        ),
    ]
