# Generated by Django 4.1.2 on 2022-10-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_command_create_date_command_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
