# Generated by Django 4.1.2 on 2022-10-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_good_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
