# Generated by Django 4.1.2 on 2022-11-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(related_name='board_tag', to='board.tag'),
        ),
    ]
